name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test with Poetry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Install dependencies
        run: poetry install --with=dev

      - name: Run pylint
        run: poetry run isort --profile black steupup

      - name: Run pylint
        run: poetry run black steupup

      - name: Run pylint
        run: poetry run pylint steupup